#!/bin/sh
### BEGIN INIT INFO
# Provides:          eq3blemqtt
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       eq3ble mqtt support
### END INIT INFO

SCRIPT=/home/pi/bt/eq3.js
RUNAS=root
NAME=eq3blemqtt

PIDFILE=/var/run/$NAME.pid
LOGFILE=/tmp/$NAME.log

start() {
  if [ -f $LOGFILE ]; then
    SUFFIX=`/usr/bin/stat -c %Y $LOGFILE`
    NEWFILE="${LOGFILE}_${SUFFIX}"
    echo "Rotating log file $LOGFILE to $NEWFILE"
    /bin/mv "$LOGFILE" "$NEWFILE"
  else
    echo 'No log file'
  fi
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  pgrep -P $(cat "$PIDFILE") | xargs -i kill -- {} && kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file was not removed: '$LOGFILE'" >&2
    update-rc.d -f $NAME remove
    rm -fv "$0"
  fi
}

status() {
  echo "Checking $NAME..."
  echo "---"
  PID=`cat "$PIDFILE"`
  echo "PID: $PID"
  PGID=`ps -o pgid= $PID`
  echo "PGID: $PGID"
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
            if [ -z "$(ps axf | grep ${PID} | grep -v grep)" ]; then
                printf "%s\n" "The process appears to be dead but pidfile still exists"
                return 2
            else
                echo "Running, the PID is $PID"
                return 0
            fi
    else
        printf "%s\n" "Service not running"
        return 1
    fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|uninstall}"
esac
